# Generated by Django 5.0.1 on 2024-01-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='idade',
            field=models.IntegerField(default=18),
        ),
    ]
